p = input('Digite algo:')
print('O tipo primitivo desse valor é: ', type(p))
print('Só tem espaços?', p.isspace())
print('É um número:', p.isnumeric())
print('É alfabetico?', p.isalpha())
print('É alfanúmerico?', p.isalnum())
print('Está em maiúsculas?', p.isupper())
print('Está em minúsculas?', p.islower())
print('Está capitalizada?', p.istitle())